// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngrqwmvuhvjkeohesbxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ncnF3bXZ1aHZqa2VvaGVzYnhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDkwMTcsImV4cCI6MjA2OTE4NTAxN30.K3uyyzjyAQ17ohQGCUFx_RiMufblLyQzvxEZHakqKrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Configurações para prevenir rate limiting
    detectSessionInUrl: false,
    flowType: 'pkce',
    // Auto-refresh apenas quando necessário (5 minutos antes de expirar)
    tokenRefreshMargin: 300, // 5 minutos em segundos
  },
  // Configurações de retry para requests
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-web'
    },
  },
  // Rate limiting configuration
  realtime: {
    params: {
      eventsPerSecond: 2
    }
  }
});